### ISSUE TITLE
Environment variables not working

### ISSUE THREAD

**Issue by adambiggs** [tony/tmuxp#124]
I can't get environment variable replacement working [as described in the docs](http://tmuxp.readthedocs.org/en/latest/examples.html#environment-variables).

To test it out, I tried adding `echo {USER}` as `before_script` and `shell_command_before`, and also tried adding `{USER}` to `session_name` and `window_name`.

But in all cases it's printed back out as `{USER}` without any variable replacement.

**Comment by tony** [comment]
What system are you running on, python version, tmux version, tmuxp version and etc?

``which tmux; tmux -V; which tmuxp; tmuxp -v; which python; python -V; uname -a; echo $USER``

How are you executing tmuxp (e.g. from Konsole in zsh, calling it from an subprocess in another script)? What shell are you using? If you check the output of `env` does everything look correct?

**Comment by adambiggs** [comment]
```
tmux: aliased to _zsh_tmux_plugin_run
tmux 2.2
/usr/local/bin/tmuxp
tmuxp 0.9.2
/usr/local/bin/python
Python 2.7.10
Darwin Adams-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
adam
```

I'm currently building tmux from master and executing tmuxp manually in zsh running iTerm. Maybe the `_zsh_tmux_plugin_run` alias is the culprit?

**Comment by tony** [comment]
I used oh my zsh on some machines, but never that plugin. I looked at it and wouldn't be surprised if it were to conflict. Try disabling the plugin, opening a new shell and see what happens.

**Comment by adambiggs** [comment]
Disabling the zsh plugin didn't fix the issue :(

I can confirm the plugin is disabled because `which tmux` is now `/usr/local/bin/tmux`.

**Comment by tony** [comment]
``zsh --version``

Can I see your config, the command your using to load it and the ``pwd``?

**Comment by adambiggs** [comment]
Sorry for the slow response, just got back from vacation.

I'm using `zsh 5.1.1 (x86_64-apple-darwin14.5.0)`, but I've also tried launching tmuxp from regular `/bin/bash` which didn't help.

Here's the test yml I'm using:

```yml
session_name: "TEST {USER}"
start_directory: "{PWD}"
shell_command_before: "echo {PWD}"
before_script: "echo {USER}"

windows:

  - window_name: "{USER} window"
    panes:
      - shell_command:
        - ls
```

And `pwd` is just a temp directory in my home folder: `/Users/adam/tmuxp-test`

**Comment by adambiggs** [comment]
After some trial and error, I got this working by adding `$`:

```yml
session_name: "TEST ${USER}"
start_directory: "${PWD}"
shell_command_before: "echo ${PWD}"
before_script: "echo ${USER}"

windows:

  - window_name: "${USER} window"
    panes:
      - shell_command:
        - ls
```

Is the missing `$` just a typo in the docs?
