### ISSUE TITLE
When using eval in shell command tmuxp stops

### ISSUE THREAD

**Issue by HarleyKwyn** [tony/tmuxp#138]
I have a script with the docker-machine command to set environment variables for docker-machine. When I run the `eval "$(docker-machine env default)" tmuxp stops running any following commands.

Anyone else experiencing this with eval? Is this expected behavior? and if it is, is there a work around?

**Comment by tony** [comment]
Is this inside a tmuxp config file? Or with the python API?

``tmux -V``, ``tmuxp -v``, ``echo $SHELL``?

Could you show the code you're using to reproduce this?

**Comment by HarleyKwyn** [comment]
With the tmuxp config file.

It's something like 
```YAML
session_name: full-stack
windows:
  - window_name: docker-ui
    panes:
    - shell_command:
      - docker machine start default
      - eval "$(docker-machine env default)"
      - docker-compose up -d
    - shell_command: gulp serve
```

Something like this. the `docker-compose up -d` command never runs

If you have docker toolkit installed a script like this will work if you create a docker machine named default. 

I'm on a Mac Book Pro running El Capitan 

Thanks for looking into this!
