### ISSUE TITLE
tmux creating an additional pane

### ISSUE THREAD

**Issue by animeshb** [tony/tmuxp#177]
I am using tmuxp to create a tmux session in my cygwin terminal. The first window is having one additional pane created. 

![tmux-session yaml](https://cloud.githubusercontent.com/assets/1550696/17773138/81cbebe6-656a-11e6-9be8-1d0e3b64fc64.png)

This is the tmuxp session yaml file I use:
```
session_name: daily
windows:
  - window_name: default
    panes:
    - focus: true
    - shell_command:
      - npm -g ls --depth=0
  - window_name: prog
    panes:
    - shell_command:
      - e
  - window_name: client
    panes:
    - shell_command:
      - cd /cygdrive/e/projects/client
  - window_name: webserver
    panes:
    - shell_command:
      - ./ngrun.sh graphs-project

```

What am I doing wrong?
