### ISSUE TITLE
Silence sell_command_before output

### ISSUE THREAD

**Issue by tutuca** [tony/tmuxp#180]
Say I want to activate my virtualenv for a window. I thought of doing somethinge along this lines:

```
session_name: tutuca
windows:
- window_name: dev
  layout: main-vertical
  shell_command_before: "workon ${session_name}"
  panes:
    - focus: true
    - manage runserver
    - npm start
```

This config pollutes the terminal with the output of `workon tutuca`

![image](https://cloud.githubusercontent.com/assets/70032/18732473/c6e3886c-8039-11e6-841b-16bfc9c98fde.png)

Is there a way to skip the output (other than redirecting it to /dev/null)?

Also the variable substitution is not working for some reason but that's probably just me :) .
