### ISSUE TITLE
Environment variable not set when launching session from tmux

### ISSUE THREAD

**Issue by k4nar** [tony/tmuxp#184]
Hello,
I have several tmuxp configuration files using `environment` to pass an env variable to the created session.
When I launch them from a terminal, the environment variables are set. But when I launch them from a running tmux session they are not.

Do you have idea what's causing this behavior?
### Failing testcase

``` yaml
session_name: test
environment:
  FOO: bar
windows:
  - panes: ['env | grep FOO']
```

Running `tmuxp load -y test.yml` shows `FOO=bar`, whereas launching the same command from a tmux session doesn't.
