### ISSUE TITLE
Only first window name considered

### ISSUE THREAD

**Issue by maljac** [tony/tmuxp#187]
Hello, 

when I create a new session `tmuxp load example` only the window name for the first window is considered. All other windows get the name of the shell (`zsh` or `bash`, depends on my default shell).

Config File:

```yaml
session_name: test
start_directory: ~/dev/
windows:
  - window_name: dev_env
    focus: true
    start_directory: envs_dev/${CUSTOMER}_environment
    layout: main-horizontal
    panes:
      - clear
      - clear
  - windows_name: another name
    start_directory: envs/${CUSTOMER}_environment
    layout: even-horizontal
    panes:
      - clear
      - clear
  - windows_name: SSH
    start_directory: envs/${CUSTOMER}_environment
    panes:
      - clear
```

Starting tmux via `tmuxp load test` (test.xml in ~/.tmuxp) results in 3 windows: `dev_env`, `zsh`, `zsh`.

My ~/.zshrc has the suggested entry at the end: 

```
export DISABLE_AUTO_TITLE=true
```

My Envionment:
- Python: 2.7.12
- Tmuxp: 1.2.2
- Tmux: 2.1
- Ubuntu: 16.04
