### ISSUE TITLE
Add variable replace with curly braces in shell_command also

### ISSUE THREAD

**Issue by ialiendeg** [tony/tmuxp#210]
I discover tmuxp yesterday and I like it's power and simplicity, but I have an special situation that I think it would be better addressed with variable replace in shell_command.

I always use different server port for all of my rails projects so browser history doesn't mix (and in case I have more than one up at the same time).

To do this I thought I can use only one tmuxp config, simpy passing it the session name and the server port. My `rails.yaml` config file is like this:

```
session_name: ${NAME}
start_directory: ~/projects/${NAME}
shell_command_before: iexport PORT=${PORT}
windows:
  - window_name: source
    panes:
      -
  - window_name: console
    panes:
      - irails c
  - window_name: server
    panes:
      - shell_command:
        - irails s -p $PORT
```

Then I can start any project in this way:
`NAME=project_name PORT=3000 tmuxp load rails`

Notice that I had to use `shell_command_before` to change the PORT value so the pane `shell_command` uses the right value and not the one set in the server's environment at the moment it goes up (when I set the first project).

I think it would be better to have variable replace also in `shell_command`, or at least, indicate this way (or a better one) in documentation so people can do things like this.

The other little issue with `shell_command` using tmux's send-key is that I have to put an 'i' in front of any order because I'm using command line in vi-mode. Maybe a new option 'vi-mode' to fix this? :)

Anyway, great work, my every day is easier with tmuxp.
