### ISSUE TITLE
Env variables are not working (macos)

### ISSUE THREAD

**Issue by Cryspart** [tony/tmuxp#225]
When I do `YOLO=yolo tmuxp load yolo`, I cannot use the env var `YOLO` inside tmux (`echo $YOLO` returns an empty string)
I have also tried `export YOLO=yolo && tmuxp load yolo` and I still cannot get the env var
The only way is to write `export YOLO=yolo` in your `.zshrc`

I am using:
- `tmuxp 1.2.6`
- `tmux 2.3`
- `zsh 5.2 (x86_64-apple-darwin16.0)`
- `macos sierra version 10.12.3`

My yolo.yaml:
```yaml
session_name: session - ${USER} (${YOLO})
start_directory: '~'
windows:
- layout: main-horizontal
  window_name: editor
  panes:
  - shell_command:
    - echo $YOLO
  start_directory: ${PWD}
```

PS Resolved:
The `session-name: session - ${USER} (${YOLO})` is working and returns session - $USER (yolo)

I have also find a way to use env var in `- shell_command: echo $YOLO` by using:
`shell_command_before: "export YOLO=${YOLO}"`at the beginning of the .yaml file

My final .yaml file:
```yaml
session_name: session - ${USER} (${YOLO})
shell_command_before: "export YOLO=${YOLO}"
start_directory: '~'
windows:
- layout: main-horizontal
  window_name: editor
  panes:
  - shell_command:
    - echo $YOLO
  start_directory: ${PWD}
```
So now I can use `$YOLO` inside tmux

Someone can close this issue

**Comment by tony** [comment]
Currently, tmuxp doesn't pass down environment variables to shell_commands, but I'm open to added the feature.

Think it'd be useful to you?  I could add it, unless you want to give it a shot. Are you interested in making a PR? It should be pretty easy, the foundation is there.

It'd be added `expandshell` to the shell_command ran in https://github.com/tony/tmuxp/blob/master/tmuxp/config.py and tests for it.

**Comment by Cryspart** [comment]
I just found out that you can actually pass env variables using `environment`:
command: `EVENT=event EDITOR=editor tmuxp load test`
```yaml
session_name: session-${USER}-(${EVENT})
start_directory: '~'
environment:
  EDITOR: ${EDITOR}
  EVENT: ${EVENT}
windows:
- window_name: monitor
  layout: main-vertical
  panes:
  - clear && echo $EVENT
  - clear && echo $EDITOR
```

or by using an external script:
```yaml
session_name: session-${USER}-(${EVENT})
shell_command_before: source .tmuxp/export_env_var.sh $VAR1 $VAR2 &&
start_directory: '~'
windows:
- window_name: monitor
  layout: main-vertical
  panes:
  - echo $VAR2
  - echo $VAR1
```

We have at least 3 ways to do it at the moment so I don't think it is a necessary feature
