### ISSUE TITLE
Adding window/panes to current session

### ISSUE THREAD

**Issue by felka** [tony/tmuxp#289]
Hi,
Using tmux 2.3.0 in Iterm2 v3.
Trying to add window to current session with following config:
```
session_name: current
windows:
- layout: main-vertical
  panes:
  - ssh -o ConnectTimeout=5 user@host
  - ssh -o ConnectTimeout=5 user@host
  - ssh -o ConnectTimeout=5 user@host
  window_name: ssh-panes
```
`tmuxp load` test asks me if I want to attach to current session. Once I answer "Y" it does nothing.
