### ISSUE TITLE
start_directory doesn't work on panes if another tmux session already exists

### ISSUE THREAD

**Issue by XanderXAJ** [tony/tmuxp#299]
`start_directory` doesn't seem to work on panes if I load a per-project tmuxp profile (via `tmuxp load .`) when a tmux server is already running that was started in a different working directory.

For example, if I start a tmux server while in `~/projects`, then try to load a project profile in `~/code`, the directory of panes with a `start_directory` will either be:
- The directory the project file is in, or;
- My home directory (`~`)

To reproduce it:
1. Create a tmux session somewhere (e.g. `cd; tmux`)
2. Create a directory (e.g. `mkdir -p ~/tmp/dir1`)
3. Add the below YAML to `~/tmp/.tmuxp.yaml`
4. Run `tmuxp load .` (either inside or outside a tmux session)

You should then observe that the working directory for many of the panes will not match what you'd expect (in the instructions I've provided, the expected working directory would be `~/tmp/dir1`).

I've included 6 different cases in the below YAML:
- `on-pane` has `start_directory` on the pane.
    - Working directory: `~/tmp`
- `on-pane-with-window-dir` has `start_directory` on the window and pane.
    - Working directory: `~/tmp`
- `on-split-pane` has `start_directory` on one split pane.
    - Working directory: `~`
- `on-split-pane-with-window-dir` has `start_directory` on the window and one split pane.
    - Working directory: `~`
- `on-window` has `starting_directory` on the window, NOT the pane.
    - Working directory: `~/tmp/dir1` (working!)
- `on-none` has NO `starting_directory` on the window or pane.
    - Working directory: `~/tmp` (working!)

Here's the `.tmuxp.yaml` YAML:

```yaml
session_name: start_directory-bug
start_directory: ./ # load session relative to this file's location (project root)
windows:
- window_name: on-pane
  panes:
  - start_directory: dir1
    shell_command:
    - echo "dir1 start_directory specified on pane"
    - pwd
  focus: 'true'
- window_name: on-pane-with-window-dir
  start_directory: ./
  panes:
  - start_directory: dir1
    shell_command:
    - echo "dir1 start_directory specified on pane"
    - pwd
- window_name: on-split-pane
  panes:
  -
  - start_directory: dir1
    shell_command:
    - echo "dir1 start_directory specified on pane"
    - pwd
- window_name: on-split-pane-with-window-dir
  start_directory: ./
  panes:
  -
  - start_directory: dir1
    shell_command:
    - echo "dir1 start_directory specified on pane"
    - pwd
- window_name: on-window
  start_directory: dir1
  panes:
  - shell_command:
    - echo "dir1 start_directory specified on window"
    - pwd
- window_name: on-none
  panes:
  - shell_command:
    - echo "No start_directory specified"
    - pwd
```
