### ISSUE TITLE
How to manually resize panes?

### ISSUE THREAD

**Issue by stianlagstad** [tony/tmuxp#320]
I'm trying this:
```
session_name: work
windows:
- window_name: window1
  panes:
  - shell_command:
    - cd dev
    - sleep 1
    - clear
    - tmux resize-pane -D 30
    focus: true
  - shell_command:
    - cd dev
    - sleep 1
    - clear
- window_name: window2
  focus: true
  panes:
  - shell_command:
    - cd dev
    - sleep 1
    - clear
    - tmux resize-pane -D 30
    focus: true
  - shell_command:
    - cd dev
    - sleep 1
    - clear
```
What I see is this:
![screencast-2017-12-01-14-25-52](https://user-images.githubusercontent.com/4340859/33484963-dcb3cab8-d6a4-11e7-89a2-1b5aaaf5edea.gif)

How should I manually resize the panes so that I get them looking the way I want them to?

```
➜  tmux -V
tmux 2.5
➜  tmuxp --version
tmuxp 1.3.5
➜  python --version
Python 3.6.3
```

**Comment by tony** [comment]
Typically manual touchups are done via keyboard commands in tmux itself (that's what I do)

Here are tmux defaults:

```
bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane
```

The other thing you can do is set a layout.

```yaml
session_name: tmuxp
start_directory: ./ # load session relative to config location (project root).
before_script: pipenv install --dev --skip-lock
shell_command_before: 
  - '[ -d `pipenv --venv` ] && source `pipenv --venv`/bin/activate && reset'
windows:
- window_name: tmuxp
  focus: True
  layout: main-horizontal
  options:
    main-pane-height: 35
  panes:
  - focus: true
  - pane 
```

There are also scripts that can be used to set stuff proportionally via scripts: https://devel.tech/tips/n/tMuXrSz9/resize-tmux-main-panes-by-percentage/
