### ISSUE TITLE
Ignore bash command in pane

### ISSUE THREAD

**Issue by Azrael3000** [tony/tmuxp#65]
At the moment empty panes are saved as - bash which starts bash on top of bash which is really unnecessary I think. So it might be good to ignore the standard shell command when saving.

**Comment by sublimino** [comment]
@Azrael3000 setting default-shell and default-command suppresses this behaviour:

    - shell_command:
      - tmux set-option -g default-shell /bin/bash
      - tmux set-option -g default-command /bin/bash
      - <some command>

**Comment by tony** [comment]
@sublimino @Azrael3000 

Does this work?

```yaml
session_name: global-options
start_directory: '~'
options:
  default-shell: ${SHELL}
  default-command: ${SHELL}
windows:
- window_name: my window name
  layout: main-horizontal
  panes:
  - shell_command:
    - top
  -
  -
```

As of yet, I don't see an example to set global options, if it doesn't work, we'll add it in.

**Comment by sublimino** [comment]
@tony I'm afraid not, it still results in a new pane spawning bash-in-bash

**Comment by tony** [comment]
@sublimino @Azrael3000  ``pip install -U tmuxp`` to 1.2.0... does it work now?

**Comment by tony** [comment]
You can also set it as a global (server-wide, all sessions) option:

```
session_name: global-options
start_directory: '~'
global_options:
  default-shell: ${SHELL}
  default-command: ${SHELL}
windows:
- window_name: my window name
  layout: main-horizontal
  panes:
  - shell_command:
    - top
  -
  -
```
