### ISSUE TITLE
Pane Attributes & Project Files, & Hook Session Termination

### ISSUE THREAD

**Issue by nfarrar** [tony/tmuxp#91]
I'm walked through the tutorial and built the sample configuration stored in ~/.tmuxp, which I load with:

```
tmuxp load myproject.yaml
```

It's awesome (and tmuxp is awesome, so thank you). I'm trying to figure out a couple next steps, and it seems the documentation is lacking on these subjects (or I'm just dense and missing it, if so, I apologize).

I'm using this configuration atm:

```
session_name: myproject
start_directory: $HOME/Projects/myproject/
windows:
  - window_name: docs
    shell_command_before: 
      workon myproject
    panes:
      - vim docs/source/*.md
      - clear
      - clear
  - window_name: dev
    layout: main-vertical
    options:
      main-pane-width: 120
    shell_command_before: 
      workon myproject
    panes:
      - clear
      - clear
      - clear
```

This gets me going, but then I have to do a bunch of manual steps to configure the panes correctly (not sure how to do all this in tmuxp):
- in window docs pane 2, I run my guard script manually (`scripts/guard.sh` - can't get the syntax right for tmux to run it)
- window docs, pane 3: cd `docs/build`, `python -m SimpleHTTPServer`
- window dev, pane 1 - cd 'crib' vim -S $HOME/.vim/sessions/crib (i can't figure out how to both change the directory and run the command)
- window dev, pane 2 - make the height smaller, name the pane 'vimux' (vim sends output here automatically)
- window dev, pane 3 - name the window to `tests`

So basically, I'm not sure how to assign "attributes" to a pane. The docs go through a bunch of examples which mostly specify:

```
panes:
  - pwd
  - pwd
  - pwd
```

But as far as I could see, the docs don't explain what 'pwd' is - it doesn't seem to actually be runing the `pwd` command, and I didn't see any examples of how to assign attributes to a pane (I probably just missed it, and I apologize for being dense).

Also, rather than putting this in ~/.tmuxp and loading it with `tmuxp load myproject.yaml`can I drop it into my project (for version control)? How do I load it?

Is it possible to hook the session termination to send a command to an application running in a pane (to shut things down cleanly?). Right now, I kill my session with `tmux kill-session`, rather than going through and  closing each vim instance, shutting down the server, stopping the `guard` process, etc. Then after, I have to clean stuff up a little.  It'd be really nice to be able to hook the `kill-session` somehow and have it terminate the server cleanly, stop the guard process cleanly, close the vim editors cleanly, etc.
